### ISSUE TITLE
Higher ping for all Java players when Floodgate is on a Bungee proxy

### ISSUE THREAD

**Issue by a6doff** [GeyserMC/Floodgate#154]
Describe the bug:

When Floodgate is on a Bungee Proxy (with or without Geyser), ping for all players (Java including) is higher. Example for a proxy with Floodgate in the same location as one without:
With:
![image](https://user-images.githubusercontent.com/67640562/121218637-34f9f700-c883-11eb-9a1b-51cf6bbc932e.png)
Without:
![image](https://user-images.githubusercontent.com/67640562/121218650-388d7e00-c883-11eb-8119-66bc6057fc4e.png)

To Reproduce:
Install Floodgate on a Bungeecord server (doesn't seem to affect Spigot)

Expected behaviour:
Just to have a regular ping for Java players?

**Comment by TheBlueBurger** [comment]
Have you upgraded to floodgate 2.0?

**Comment by a6doff** [comment]
Yes, forgot to mention that. That's a new installation and haven't used 1.0 before either

**Comment by Bart0o** [comment]
Same problem. It has occurred since I upgraded to floodgate 2

**Comment by DominatorRUS** [comment]
I have same issue with Floodgate 2.0. Both: Java and Bedrock players extremely lagging when Floodgate 2.0 installed on BungeeCord side.

**Comment by Bart0o** [comment]
find the solution: moved everything from a vps to a dedicated one.

**Comment by DominatorRUS** [comment]
> find the solution: moved everything from a vps to a dedicated one.

My server is located at OVH dedicated server machine with 1Gbit/s channel, AMD Epyc 7371 (16c/32t), 128GB DDR4 RAM. I this it's quite enough for small server with 150 online.

**Comment by a6doff** [comment]
> find the solution: moved everything from a vps to a dedicated one.

I literally have a Ryzen 9 5950X with 128GB RAM so I don't think that'd help

**Comment by Stixil** [comment]
Bump, experiencing this issue with my server and it's been very frustrating.

**Comment by Camotoy** [comment]
For anyone experiencing this issue, it would be helpful for us if you could provide a Geyser dump, your Linux distribution (if relevant), where you got your Java software from, your CPU model, and your Spigot/BungeeCord configurations.

**Comment by a6doff** [comment]
> For anyone experiencing this issue, it would be helpful for us if you could provide a Geyser dump, your Linux distribution (if relevant), where you got your Java software from, your CPU model, and your Spigot/BungeeCord configurations.

Debian 10 and here's a dump I sent on your Discord before opening that issue but the behaviour didn't change: [https://dump.geysermc.org/6VlM0OkKcBAXcChvK1Dk10Wt3flLVfkn](url)

**Comment by Stixil** [comment]
Geyser Dump: https://dump.geysermc.org/wpAqkmuTy0iXno4KMqZ5jEPvTDlD6IOY

Java Version:
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode)
glibc version 2.31

Alpine Linux (docker image)
Ryzen 7 3800x

Spigot Config:
[23:10:11 INFO]: This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
https://pastebin.com/R3hXnLVY

BungeeCord config:
[23:10:30 INFO]: This server is running Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437 by md_5
https://pastebin.com/43UXEGHp


> For anyone experiencing this issue, it would be helpful for us if you could provide a Geyser dump, your Linux distribution (if relevant), where you got your Java software from, your CPU model, and your Spigot/BungeeCord configurations.

**Comment by Camotoy** [comment]
Oh, totally forgot about one thing that could really point us in the right direction!

```
Spark is a plugin that helps you monitor performance for you server.
https://spark.lucko.me/download

To record performance on your server use:
/spark profiler --thread * --timeout 60
This will run for 60 seconds then it will automatically stop.
It'll probably lag the server a good deal but it'll give us a link we might be able to process.
```

Run that command as the lag is occurring.

**Comment by alyx** [comment]
Hey there!

Following up from @Stixil, our Spark output is: https://spark.lucko.me/yuncilB7Fm

**Comment by Tim203** [comment]
Thanks for the Spark profile, but I can't find either Geyser or Floodgate in that profile.

**Comment by toinouH** [comment]
@Tim203 Maybe because it's one made on the backend server. I would ask for a bungee spark profile.

**Comment by Tim203** [comment]
Ah yeah, forgot that it only seems to happen on Bungee. Would be nice to get a Spark profile of the Bungee yeah

**Comment by Stixil** [comment]
Spark isn't a bungeecord plugin. Is this something you really need to fix this issue? That's not something we're able to provide unfortunately

**Comment by Camotoy** [comment]
Spark is a BungeeCord plugin. Try installing it anyway.

**Comment by embeddedt** [comment]
> Spark isn't a bungeecord plugin.

Actually, it is:

https://ci.lucko.me/job/spark/

> BungeeCord: download spark.jar and use the command /sparkb to control the plugin.

**Comment by Stixil** [comment]
Cool, I'll try it if we ever install floodgate again. We removed it because of the issue.

**Comment by a6doff** [comment]
I had personally tried Spark before even making the issue and I don't think there was anything noticeably weird on it but I'd have to check

**Comment by Stixil** [comment]
Hopefully something shows up on yours, it'd be great to have a resolution to this one for everyone

**Comment by a6doff** [comment]
Yeah I'll try tomorrow

**Comment by Camotoy** [comment]
For those afflicted, do try https://github.com/GeyserMC/Floodgate/pull/165/checks, which may solve the issue?

To download a pull request (or a "PR") you need to:
1. Make sure you are signed in with a GitHub account
2. Follow the pull request link that was sent to you
3. Follow the guide on this picture

**Comment by Konicai** [comment]
![](https://i.ibb.co/tCcB1Qp/PR1.png)

**Comment by rafaelsms** [comment]
I'm not using a proxy, but latency seems to spike too. I'm using latest spigot and #165's build.

```
This server is running CraftBukkit version 3159-Spigot-f773da8-887bc05 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
```

Performance seems better (world loads faster), but not quite there yet (still getting killed after connecting).

I'm getting this issue with properties. I deleted the folder thinking it is something that didn't updated, but the issue is still there. (The log is after deleting the folder).

Some NPEs with properties: https://paste.gg/p/anonymous/d221d05cf19d495fb57ed9ae23826a61
Second run with spark: https://paste.gg/p/anonymous/8e8cca4222ab47f6a505f943735e6cfb
Spark report: https://spark.lucko.me/sYvJz5JMuO

Hopefully this can help you!

**Comment by Camotoy** [comment]
If anything, that's a corrupt Floodgate jar, or it did not get built correctly over GitHub.

**Comment by rafaelsms** [comment]
Redownloaded and reextracted, same checksum. I believe it didn't get built correctly. If you need me to test anything, I'm available.

**Comment by Camotoy** [comment]
The change is now in master if you would like to re-test.

**Comment by rafaelsms** [comment]
Spark report: https://spark.lucko.me/hcVC8GfX8a
Log: https://paste.gg/p/anonymous/d8eda9436f9b44ac88592b09d1b0fbdc

But I removed floodgate and the issue still happened.. (timed out on second attempt, the first minute was fine). So I don't know what could be causing this.
Spark report (without floodgate): https://spark.lucko.me/lWj86f19Q2
Log: https://paste.gg/p/anonymous/377e0346a90d4981ad0588ad37834231

**Comment by Camotoy** [comment]
An additional change has been made into master if you wish to try.

**Comment by rafaelsms** [comment]
spark upon login: https://spark.lucko.me/maBAHA6Xj2
I didn't got into playing, my Minecraft BE just kept floating on a blank world. This is using latest Geyser and floodgate on a Spigot server. TPS always drops a bit upon login and many people timeout together, but I didn't get a chance on profiling as it happens at what seems random.

I can reproduce the high latency issue on Geyser alone (happens after teleporting, walking, the block breaking animation don't appear and it just stops receiving data even though I can type commands and it logs on my console) , but I can't test if there's a CPU spike at login without floodgate on my VPS.

**Comment by a6doff** [comment]
Seems pretty much the same than the previous versions of 2.0 if not more laggy with some random IP Forwarding issues and random disconnects

**Comment by Camotoy** [comment]
Geyser itself should not be affecting the latency of other players unless it's just going ham on the CPU/memory.

**Comment by Camotoy** [comment]
Rafael, looks like I might have an idea of what's going on in your Spark report.

**Comment by Camotoy** [comment]
[Geyser-Spigot.zip](https://github.com/GeyserMC/Floodgate/files/6705375/Geyser-Spigot.zip)

Here is a custom Geyser build, if you trust it @rafaelsms . It checks to see if the chunk is loaded before grabbing a block from the world.

**Comment by rafaelsms** [comment]
Sadly, I could reproduce the issue. It was a bit slower to do it than usual, so it seems to be a step in the right direction :)

Spark report: https://spark.lucko.me/iYJ4bZdhHj (sorry I made it long, I couldn't reproduce the issue very easily this time)

I couldn't record on my Windows 10 edition, so I used my phone. The freeze used to happen on a simple teleport, now it is much harder to reproduce, which is nice. 
Console recording: https://youtu.be/O1K3gK34OQ8
Phone recording (server desync starts a bit after 2:20): https://youtu.be/98v6OcJU4BI

**Comment by itsDrav** [comment]
Hello! I don’t know if anything was done towards fixing this issue, but I can add that, from my experience, this happens even if there are no bedrock players connected to the proxy. At least on my proxy the ping lag is so noticeable that players lag forward every couple seconds. I’ve also witnessed nearly an entire servers ping go up by 500 for every player connected, which happens in 5-20 second intervals. This could just be the tab plugin i use to display the ping, but with the lag in player movement that happens as well would make me assume it’s correct. CPU and ram wise nothing seems out of the ordinary, proxy console also seems normal, and removing floodgate seems to fix the issue. If there’s anything i can add to this to help get this issue fixed I would be happy to share!

**Comment by itsDrav** [comment]
Okay, I have done some further testing with this just now, and the problem actually seems to come down to floodgate clashing with server manager plugins? The ping lag didn't exist when I tried running a clean waterfall + floodgate, but does exist when both AJQueue+ and BungeeServerManager are installed. Just one of them have to be installed for the ping issue to be seen. 
Links to the plugins: 
AJQueue: https://www.spigotmc.org/resources/ajqueueplus.79123/
BungeeServerManager: https://www.spigotmc.org/resources/bungeeservermanager-bungeecord-mysql.24837/
To clarify:
- All current waterfall plugins: Ping Issues
- All current waterfall plugins - floodgate: No Ping Issues
- Clean waterfall + floodgate + AJQ or BungeeServerManager: Ping Issues
- Clean waterfall with AJQ and BSM but no floodgate: No Ping Issues

If you still need the things mentioned I can supply them, but since this seems to be an issue between plugins, I didn't see a need. I can also contact the plugin dev's for the two plugins if its more of an issue on their end. 

An easy way to test this is by running a clean waterfall instance, installing the mentioned plugins, and have two java accounts on a single server. Just watch the second account run around and they will pause and teleport forward every 5-10 seconds, or just have both accounts in creative mode and spam punch the other, the hits will delay every so often.

**Comment by itsDrav** [comment]
I'm still experiencing this issue and was wondering if this can be fixed floodgate side, or if I should go and see if the individual dev's of the plugins can somehow get this fixed. I can't really remove floodgate as a big portion of our players rely on it. 
Some other things that may be useful that were mentioned to include above: 

Spark - 
With Floodgate, AJQ, and BPM: https://spark.lucko.me/lUF6pWmKud
With Floodgate but no AJQ and BPM: https://spark.lucko.me/vFqW0fggGt
Without Floodgate, with AJQ and BPM: https://spark.lucko.me/2GYV2MiHgg

Geyser dump - 
With Floodgate, AJQ, and BPM: https://dump.geysermc.org/qL1QDQcWmZJb9UMydC1x7zwIOCcXfCvb
With Floodgate but no AJQ and BPM: https://dump.geysermc.org/H9vkMa4R60tvHOZqgto7lNOgTHNE3ciW
Without Floodgate, with AJQ and BPM: https://dump.geysermc.org/dkKUpHCMV90lNGkjHNqtr6qyYzX4ZtEt

CPU: AMD Ryzen 9 5950x

Java Version : Currently testing on Java 8 but ping lag has been experienced on Java 11 and Java 16

Bungee config: https://github.com/GeyserMC/Floodgate/files/6925997/config.txt

I am pretty sure both AJQueue and BedrockPluginManager are open source so if the code is needed to see possible areas of conflict, those are available as well.  

I will add, this problem is seen with and without geyser being installed on the server, and it is being tested on a proxy with only my java account being online, no one else. Tested different floodgate options, turning send floodgate data to servers from true to false, still, the lag is seen. 

If there is anything else I can add that can get this issue looked into and fixed, let me know, as the ping lag gets really annoying sometimes.

**Comment by Camotoy** [comment]
My apologies; I meant to look further into it and didn't want to update until then. I tested with my FreeBSD server that has MySQL plus BungeeServerManager and did not experience the lag. I'll try to test on a Linux-based platform soon.

**Comment by itsDrav** [comment]
This is on a proxy with just BSM, floodgate and bungeeguard:

Lag in place:  
https://user-images.githubusercontent.com/60583244/128064841-8bd957c2-c305-4e2e-bfa6-defa4c323f6b.mp4

Lag while hitting (I was spam clicking the entire time): 
https://user-images.githubusercontent.com/60583244/128064976-b95d9107-a767-42ce-a456-a6f7cca20a78.mp4

Weird ping tab lag (this is on a network server with all plugins):
https://user-images.githubusercontent.com/60583244/128065112-f72d0561-307c-4875-ae42-44131b128f23.mp4

I cannot recreate the hitting issue when running only floodgate or only BSM.

**Comment by Tim203** [comment]
Hi, Floodgate build 29 has just been released which should fix this issue. Let me know if you're still having problems

**Comment by iVillager** [comment]
I think this is not solved, I'm having the same problem rn with the last build.

This shows what's going on 
https://spark.lucko.me/IwXq1RQT4q

**Comment by Chew** [comment]
Please open a new issue or talk to us on Discord.
