### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by Git2Gud** [GeyserMC/Floodgate#226]
I'm back with more issues that are probably really easy to fix! My friends trying to join from bedrock get an error that says "Unable to connect to world". My friend on java was able to connect fine. The user in question's uuid is on the whitelist. He used the correct [ip]:19132 that we (java) were able to connect to (sans port). Since it's quite an un-detailed error message, if you know the cause that would be helpful. thank you!

[geyser dump since it was suggested last time :)](https://dump.geysermc.org/GvC7lLji9jvCEt3eLtrd2HV8cqY3hTtb)

**Comment by Chew** [comment]
I'll give you some tips here, but generally, this should be handled on our [Discord server](https://discord.gg/geysermc)

1) Does the IP work if you enter it into https://mcsrvstat.us? This will bring back a response if the server is active.
2) If it does, have your friends try restarting the app. 
3) Ensure the port is actually open and is replying. If you use a host found in the [hosting provider list on the wiki](https://github.com/GeyserMC/Geyser/wiki/Supported-Hosting-Providers), follow their guide, otherwise, ensure UDP port 19132 is open for connections.

**Comment by Git2Gud** [comment]
1. It's active, but with the bedrock box checked it doesn't find anything.
3. I'm using AWS to host with [this docking image](https://github.com/vatertime/minecraft-spot-pricing). Are you aware of a method to see if the port is open for connections through the command line? I have ssh set up to access the server files.

**Comment by Camotoy** [comment]
Closing since we don't keep network issues like these open on the issue tracker. Discussion can still continue here if need be!
