### ISSUE TITLE
Config option to pick username to join as

### ISSUE THREAD

**Issue by Siiriiks** [GeyserMC/Floodgate#243]
I thought this would be a good addition because bedrock players can have the same username as each other and are required to pay to change them on some services. It would help differentiate them from each other and allow them to pick what username they decide to use.

It could work similarly to how Geyser does without floodgate on an online mode server but instead prompts for a username instead of login details and once a username is entered it links it to that users xuid like the account linking.

It would also be handy for servers using authentication plugins, for example on an offline server, because another user might already be using their bedrock username so they wouldn't be able to play.

Could be used in combination with name prefixes or some external/other method to prevent bedrock and java having the same usernames (Such as only allowing non registered java usernames)

**Comment by Camotoy** [comment]
Bedrock players, as far as we know, cannot share an Xbox Live name with another player.

**Comment by Siiriiks** [comment]
I'm not sure how recent it has been but they released a new gamertag system which includes an ID after it like Discord does it allowing multiple users with the same gamertag. I'm unsure if it is fully supported in Minecraft yet but I still think it would be nice for people who are stuck with a username or if theirs is already used on a server they want to join.

**Comment by Chew** [comment]
Minecraft would add those 4 digits at the end of the name, now if someone had that name#digits as their namedigits I'm not sure but I'd assume it'd be handled...

**Comment by Siiriiks** [comment]
Don't worry about bedrock having the same usernames then. I still think it would be a nice feature to have and could remove the need for prefixes on some servers by stopping clashes with java usernames.

**Comment by Tim203** [comment]
That'd be a complex system to make, because you have to think about various things (if we're just talking about your latest message, being able to remove the prefix for some people), not to mention a system like that would be confusing for players (because who is a Bedrock player and who isn't?)

I don't think that a feature like unofficial usernames is something that should be in Floodgate. Not every behaviour of Minecraft Java Edition can be converted to Bedrock Edition (I'm speaking about being able to change your username every month on Java, for free), and we have to draw a line somewhere.

Thanks for your suggestion though.
