### ISSUE TITLE
Errors not visible from rcon

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [GeyserMC/Floodgate#261]
>  If you don't get a response from that command as well, please open a separate issue saying that commands don't respond when rcon is used.

It looks like this _specific_ error [isn't being routed](https://github.com/GeyserMC/Floodgate/blob/a8829c6d57979a7c66db4b54cecc60cf991293d7/common/src/main/java/org/geysermc/floodgate/command/WhitelistCommand.java#L141) the way it should be; [other floodgate command errors](https://github.com/GeyserMC/Floodgate/blob/a8829c6d57979a7c66db4b54cecc60cf991293d7/common/src/main/java/org/geysermc/floodgate/command/WhitelistCommand.java#L170) do have error statuses replied over the "normal" channel (i.e. the same channel as stock commands); it's only #206 that's being sent to the logs rather than being returned:

```
$ mcrcon
Logged in. Type 'quit' or 'exit' to quit.
>floodgate
Available subcommands are:

firewall - Check if your outgoing firewall allows Floodgate to work properly
>floodgate firewall
>fwhitelist list
Invalid Command Syntax. Correct command syntax is: /fwhitelist add|remove
>fwhitelist add 00000000-0000-0000-0009-01fe37fa8775
00000000-0000-0000-0009-01fe37fa8775 has been added to the whitelist!
>fwhitelist remove 00000000-0000-0000-ffff-ffffffffffff
Nothing has changed. 00000000-0000-0000-ffff-ffffffffffff was not on the whitelist so they couldn't be removed
>whitelist add xx_nonexistentplayer_xx
That player does not exist
>fwhitelist add skyridersam
>
```

```
[13:22:09] [RCON Listener #1/INFO]: Thread RCON Client /0:0:0:0:0:0:0:1 started
[13:23:11] [pool-9-thread-1/ERROR]: [floodgate] Got an error from requesting the xuid of a Bedrock player: Unable to find user in our cache. Please try specifying their Floodgate UUID instead
```

**Comment by JamesTheAwesomeDude** [comment]
It looks like it might actually be due to a missing translation:

https://github.com/GeyserMC/languages/search?q=UNEXPECTED_ERROR

**Comment by Tim203** [comment]
So I looked into the source code of the RCON classes in the Minecraft Server and found out why it doesn't work.
It's because RCON has a weird implementation. It depends on being single-threaded, and it depends on sync command execution.

The output (which will be send to a CommandSender) is being added to a string buffer, and every time the command executed (as in the method inside the CommandExecuter has returned), it'll be returned to the RCON.
But the catch is that it'll only be returned to the RCON when the command has been executed. Every time it receives a new command, the stringbuffer (which very likely contains the response from the async command execution) is cleared.

I don't think that there is a way to fix this, but I'll leave it open for a while in case someone does know how to fix it properly.

**Comment by Gaming32** [comment]
I'm guessing that the easiest and best fix would be to patch the server itself. Probably on Spigot.

**Comment by Tim203** [comment]
I'll close this issue because there is no easy way to fix this.
