### ISSUE TITLE
Jitter when looking around

### ISSUE THREAD

**Issue by Elryyyyyyyy** [GeyserMC/Floodgate#340]
When i join a Server that has floodgate installed my looking around is all jittery and weird.

**Comment by Konicai** [comment]
With such little information there is very little we can do with this bug report. This likely isn't a Floodgate issue though since Floodgate only handles authenticating Geyser players, and Geyser handles the actually connection and translation. Have you experienced this on servers that don't have Floodgate (e.g. using GeyserConnect to connect to a Java Edition only server)?

My two guesses is that you're on an older phone with low framerate because of entities or structures on the server, or your coordinates are too large and Bedrock Edition is suffering from [distance effects](https://minecraft.fandom.com/wiki/Bedrock_Edition_distance_effects).

If you can provide server information and reproduction steps then feel free to create an descriptive bug report on https://github.com/GeyserMC/Geyser
