### ISSUE TITLE
Is it possible to add an option to choose to use the offline mode UUID instead of the bedrock's XUID?

### ISSUE THREAD

**Issue by MelodyYuuka** [GeyserMC/Floodgate#346]
I am using Geyser Standalone.
Because my server is offline mode server, I want to get the player's real ip while getting the UUID in offline mode.
When I use "auth-type: offline", players can log into the server with their Java Edition name, no problem
When using floodgate, because the XUID of Bedrock Edition is forwarded at the same time, the UUID in offline mode cannot be used to enter the server.
But if I don't use floodgate, it seems that I can't achieve the effect of getting the real ip, which troubles me very much.
Is it possible to add an option to choose to use the offline mode UUID instead of the bedrock edition's XUID? Like when ”auth-type: offline”.
I would be grateful if you could solve my problem.

(Please excuse my broken English. XD)

**Comment by Camotoy** [comment]
This is not something we're interested in unfortunately. Thanks anyway.

**Comment by Konicai** [comment]
We don't support offline mode servers. If you want to link bedrock accounts to java edition accounts, you can use floodgate's linking system. You might need to use local linking instead of global linking because global linking requires real java edition accounts. You can learn more about it on the geyser wiki.

If you want offline mode UUIDs because your bedrock player's already have their playerdata saved to offline mode UUIDs, you're just going to have to manually migrate their playerdata to the new floodgate UUIDs.

Not using the floodgate UUID would break many things, such as bedrock players joining with the same name as a completely different person's java edition account (if using an offline mode server), so thats not going to happen.

**Comment by GuilhermeWerner** [comment]
One thing that just happened on my server was two different people logged in with the same account because the floodgate UUID was the same, they both shared the google account.

Will I have to configure local linking then?
