### ISSUE TITLE
Floodgate grabs the wrong skin

### ISSUE THREAD

**Issue by ShadowShok** [GeyserMC/Floodgate#422]
My nickname on minecraft java is "0ShadowShok0" but for some reason it grabs a skin from a player called "shadowshok".
This may be a conflict with my gamertag on xbox, which is "ShadowShok".

**Comment by ShadowShok** [comment]
I forgot to mention i connected the java and bedrock accounts, so it should get the skin from the java username instead of the bedrock one.

**Comment by Tim203** [comment]
I am not sure if this is possible without other plugins modifying Floodgate behavior. The way that skins work is that they're connected by their UUID (not username).

So let's say that Floodgate failed to see your linked account at all, it'd use the Floodgate UUID. This wouldn't give you a skin at all (without the Floodgate skin service.)
Let's say that it used your gamertag, but the linked account UUID. This would give you the skin of your Java account since it uses your linked account's UUID.

In no situation we'd know the Java UUID of the user with the same username as your gamertag. You'd have to fetch that from the Mojang servers, which isn't something that Floodgate nor Geyser does.

It sounds like you have a login plugin or some kind of skin restorer plugin, which we don't support.
