### ISSUE TITLE
Incompatability with fabric proxy lite

### ISSUE THREAD

**Issue by RealKomander** [GeyserMC/Floodgate#467]
Some time ago I created an issue here (can't find it for some reason, probably got hidden of I left it on another geyserMC project), the problem is that I still can't update my fabric servers in my network to 1.20.2 because floodgate is incompatible with fabric proxy lite - a mod that is necessary for adding fabric servers to a velocity proxy. I've left an issue on fabric proxy lile github, and they asked me to contact you.

Server crashes on startup like this:
[latest.log](https://github.com/GeyserMC/Floodgate/files/13403676/latest.log)

To replicate, install latest floodgate and fabric proxy lite together (both mods work fine when separated)

**Comment by onebeastchris** [comment]
Not sure why you're opening the third issue now (after https://github.com/GeyserMC/Floodgate-Fabric/issues/110 and https://github.com/GeyserMC/Floodgate-Fabric/issues/109) - this is still a fabric proxy lite issue (as you've also stated [here](https://github.com/GeyserMC/Floodgate-Fabric/issues/109#issuecomment-1788870993)).

Please report this to FabricProxyLite instead. I've also asked in the kyori discord (since the conflict is between FabricProxyLite + theie adventure-platform-fabric lib), and it looks like the first does some funky transformations that seem to be broken.

**Comment by onebeastchris** [comment]
I'll leave a comment on the FabricProxyLite issue too

**Comment by RealKomander** [comment]
I've reported it to them and they said to report it to you
https://github.com/OKTW-Network/FabricProxy-Lite/issues/65

**Comment by RealKomander** [comment]
Alright, I see in that thread, thank you so much for helping

**Comment by onebeastchris** [comment]
resolved with https://github.com/GeyserMC/Floodgate-Fabric/pull/112
