### ISSUE TITLE
add mojimap support 🙏 

### ISSUE THREAD

**Issue by ThrowerWay** [GeyserMC/Floodgate#502]
for paper 😄

**Comment by onebeastchris** [comment]
What error are you getting?

**Comment by onebeastchris** [comment]
Paper 1.20.5 is supported, and paper does remap spigot-mapped calls to mojang ones. The latest version of floodgate already works on 1.20.5 Spigot, and also on 1.20.5 Paper

**Comment by onebeastchris** [comment]
I wouldn't call that feature bloat as it allows (e.g. us) to make a plugin using internals compatible with both spigot and paper at the same time.

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Floodgate/commit/343023fdaf542cbcac6bb31865d01fef598afded
The dev branch will add support for mojang mappings. If you feel that strongly about them, feel free to backport that to the current master branch and create a PR - imo, given that paper's remapping feature is opt-out instead of opt-in, i think it's fine to rely on that for that time being

**Comment by Tim203** [comment]
Note that just that commit is not enough to support the latest Paper changes.
All new features are added to the dev branch and master only receives updates to support the latest versions.
Since Paper offers Spigot compatibility by default we won't be adding it ourselves, but yeah I don't think we'd reject a PR because of it.
