### ISSUE TITLE
Cannot invoke "java.util.Locale.getLanguage()" because "locale" is null (versions prior to 1.20.1)

### ISSUE THREAD

**Issue by Z3r0xh** [GeyserMC/Floodgate#506]
Java players cannot enter version 1.20.1 with the latest floodgate update.

I leave the debug of my proxy,

https://mclo.gs/s6lY2re

**Comment by onebeastchris** [comment]
That's a NullCordX issue - getLocale() for some reason returns null there.

**Comment by onebeastchris** [comment]
waterfall is EOL, try bungee?

**Comment by BoomEaro** [comment]
> waterfall is EOL, try bungee?

BungeeCord - the same:
https://pastebin.com/Kdntn4f2

I can assume that the geyser client sends ClientSettings too late or does not send it at all.

**Comment by Z3r0xh** [comment]
> waterfall is EOL, try bungee?

With bungeeCord https://mclo.gs/fEcWeYT

**Comment by onebeastchris** [comment]
I'll take a look in a sec

**Comment by onebeastchris** [comment]
Unable to reproduce with `This server is running BungeeCord version git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:18eae8a:1842 by md_5` - installed plugins are just Geyser/Floodgate. I can join fine with both Bedrock edition, as well as Java edition. 
Please verify that this is an issue with just Geyser and Floodgate installed

**Comment by Z3r0xh** [comment]
> @xism4 are you able to reproduce the error with just Geyser/Floodgate on BungeeCord? I've tried to, i cannot reproduce it - joining seems to work fine on both Java and Bedrock clients. If you are seeing an error, please share it in full on a reproducible setup

Only with geyser and floodgate
https://mclo.gs/o9p2a6d

**Comment by onebeastchris** [comment]
I'm not seeing any errors from Geyser or Floodgate in that log

**Comment by Z3r0xh** [comment]
> I'm not seeing any errors from Geyser or Floodgate in that log - that's just the proxy disconnecting players by the looks of it

I just tried with the previous build (a44e3a5) and it does not give an error when entering, this was with the last build that is giving these problems

**Comment by Z3r0xh** [comment]
> > I'm not seeing any errors from Geyser or Floodgate in that log - that's just the proxy disconnecting players by the looks of it
> 
> I just tried with the previous build ([a44e3a5](https://github.com/GeyserMC/Floodgate/commit/a44e3a5df8e3823e548c59d158f65cd7908a96b7)) and it does not give an error when entering, this was with the last build that is giving these problems

I just did a clean installation and it only doesn't allow java players with the latest Floodgate update to access if they are on 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20.1,

**Comment by xism4** [comment]
> I just did a clean installation and it only doesn't allow java players with the latest Floodgate update to access if they are on 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20.1,

That is a change from spigot core

**Comment by onebeastchris** [comment]
What server version/type are you using on your backend server? (cc @Z3r0xh )?
I've been able to connect with a 1.20 java client fine on a 1.20.2/1.19.4 backend with the latest version of bungee/geyser/floodgate.

**Comment by Z3r0xh** [comment]
> What server version/type are you using on your backend server? (cc @Z3r0xh )? I've been able to connect with a 1.20 java client fine on a 1.20.2/1.19.4 backend with the latest version of bungee/geyser/floodgate.

my lobby is 1.8.8 using pandaspigot.

The other spigot are pufferfish 1.20.4 in the latest update

I am using the latest version of geyser and floodgate

**Comment by Z3r0xh** [comment]
> What server version/type are you using on your backend server? (cc @Z3r0xh )? I've been able to connect with a 1.20 java client fine on a 1.20.2/1.19.4 backend with the latest version of bungee/geyser/floodgate.

Could you send me your logs to see? I've been testing these days and I can't get them to work with my java players.

**Comment by Sckaletz** [comment]
I can confirm this issue. We've been having the same problem since Floodgate build #102. 
We have Geyser #526 and Floodgate #102 on our Spigot Bungeecord along with Floodgate #102 on our backend servers running Paper 1.8.8.
Without the Floodgate on both Bungeecord and Paper, Java players with 1.20.1 is able to join fine, but with Floodgate, they get the error: "NullPointerException : Cannot invoke "java.util.Locale.getLanguage()" because "locale" is null @ org.geysermc.floodgate.util.Utils:87"

Same problem happens to our Bedrock players on version 1.20.81. 

Before #102 everyone was able to join fine.

https://dump.geysermc.org/zSJsUCx5dLkzYhL1vEmO0ZbwJHWHud1X

Error on Bungeecord: 
https://pastebin.com/2pV5dJY7

Error on Paper WITH Floodgate: 
[11:20:14] [Server thread/INFO]: Sckaletz lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe

Error on Paper WITHOUT Floodgate, but Floodgate still on Bungeecord: 
[11:18:19] [Server thread/INFO]: Sckaletz lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
[11:18:27] [Server thread/INFO]: ^Floodgate^>ixndsmxcxjLw9UNJ!bIXeOrXAV2AYRu27qhf25IGJe7wlVRwxAu4zaw2wTNTLu52cc9NzmELTe/fXEfTUZrsRYWZ9yhL4fW8RwEfIQckE61PFlXWNq9jHuHYW0G1zCdsv9KBL7g2rm9d34m5mVxuXOff4ZXQTZd8V:59187 lost connection: Internal Exception: java.lang.IllegalArgumentException: Invalid UUID string: 120.21.132.22

**Comment by Z3r0xh** [comment]
> On the Spigot platform we only make sure we're compatible with Spigot and Paper, but we also offer Folia support. Please try to replicate it with one of those 3 server software and otherwise report the issue to the fork you're using.

Hello Tim, after doing tests I can tell you that it is not a problem with the mc versions.

I have been testing velocity with papers in both 1.8.8 and 1.20.4 and they worked well.

I have decided to change the proxy to bungeeCord and it has automatically stopped working and started giving the error, so the problem is only in bungeecord

https://mclo.gs/mSgIStN

![image](https://github.com/GeyserMC/Floodgate/assets/138524212/8e85399d-467c-4fd6-b465-148e841c8b99)

**Comment by onebeastchris** [comment]
Should be resolved in the latest build. Thanks for reporting!

**Comment by Z3r0xh** [comment]
> Should be resolved in the latest build. Thanks for reporting!

Thank you very much for reviewing and fixing the error!
