### ISSUE TITLE
Add the ability to disable floodgate UUID generation.

### ISSUE THREAD

**Issue by chelminski** [GeyserMC/Floodgate#81]
Add the ability to disable the generation of separate UUIDs by floodgate so that Java and Bedrock players do not have to pair their accounts via command, the accounts would use the same UUID based on the player's nickname only.

- This is very necessary for people who need floodgate to see the real IP address of the user.
- This is helpful for people who have their own user verification system (login and registration).
- Very helpful for servers with Offline Authentication for Administrators that need bedrock player IP without add-ons.

**Comment by HelveticaToast** [comment]
I'm having trouble understanding this, remove uuids from Floodgate? If players didn't have a uuid, a lot of things would break.

**Comment by chelminski** [comment]
I'm sorry if something is incomprehensible, but English is not my primary language.What is incomprehensible? I believe administrators should have the option to disable floodgate UUID. Currently, he himself needs bedrock folks to connect to the UUID like the folks from non-premium Java. This would solve a lot of my problems.

**Comment by chelminski** [comment]
> I'm having trouble understanding this, remove uuids from Floodgate? If players didn't have a uuid, a lot of things would break.

I'm sorry if something is incomprehensible, but English is not my primary language.What is incomprehensible? I believe administrators should have the option to disable floodgate UUID. Currently, he himself needs bedrock folks to connect to the UUID like the folks from non-premium Java. This would solve a lot of my problems.

**Comment by HelveticaToast** [comment]
> Currently, he himself needs bedrock folks to connect to the UUID like the folks from non-premium Java.

good luck trying to get the developers to add something that helps servers that support piracy.

**Comment by chelminski** [comment]
> > Currently, he himself needs bedrock folks to connect to the UUID like the folks from non-premium Java.
> 
> good luck trying to get the developers to add something that helps servers that support piracy.

This would work the same way for premium servers. Players would have to enter a password, but their accounts would automatically be linked.

**Comment by HelveticaToast** [comment]
where would this "password" be obtained from? What about the people that don't want their account linked?

**Comment by chelminski** [comment]
> where would this "password" be obtained from? What about the people that don't want their account linked?

Most players use bedrock and Java is an additional option. I think that no one sees a problem with the fact that he can enter from several devices at the same time using one nickname and password. It is much easier to configure than the current solution, especially for people who do not use English.

**Comment by AlysaaKobe** [comment]
> > where would this "password" be obtained from? What about the people that don't want their account linked?
> 
> Most players use bedrock and Java is an additional option. I think that no one sees a problem with the fact that he can enter from several devices using one nickname and password. It is much easier to configure than the current solution, especially for people who do not use English.

Every account needs an uuid, even cracked player. It's just how every server handles player data like inventory,current position etc... Therefore it can't be removed or disabled. Also would be a big security issue

**Comment by RednedEpic** [comment]
From what I can gather, it seems this issue is more about having people who share the same usernames on both platform automatically inherit the UUID of what they have on Java. Say I own the username "Redned" on both platforms, if I join through Bedrock, it will automatically use my Java UUID. 

I don't see much of a practical use for a system like this if I'm being honest. In my case, I don't own the account "Redned" on Bedrock. If the owner of that username were to join a server with Bedrock, and I joined it with Java, would I have their inventory? Would I be locked out of playing on the server? Would I have to choose a new username? How would my UUID be assigned? In a case like this, I can't see a good solution to the problem that you are trying to solve here, which is automatically linking. Perhaps I'm missing something, but I feel like any solution we try and implement here goes beyond what Floodgate is aiming to accomplish. 

Any solution involving "choosing a new nickname" would go beyond the scope of this project ultimately. I think the way we have it now is the best way to handle it, and if you want people to have different nicknames, I would suggest installing a nickname plugin and using a plugin such as TAB to reflect this above their head as well.
